### ISSUE TITLE
Network Drive Repo Link from UI has incorrect endpoint

### ISSUE THREAD

**Issue by iamhowardtheduck** [elastic/enterprise-search-network-drive-connector#23]
The Kibana UI of 8.3.1 has an incorrect link to: 

https://github.com/elastic/enterprise-search-network-drive-connector

It should link to:

https://github.co
![NetworkDriversConnectorGitHubLink](https://user-images.githubusercontent.com/11168913/177670422-d6eb675b-3cc2-4fd6-b8fe-2db2ec73441d.png)
m/elastic/enterprise-search-network-drives-connector/

![GitHubScreenshot](https://user-images.githubusercontent.com/11168913/177668624-17b047dc-372f-459c-b222-ac3d77150e7d.JPG)

**Comment by serenachou** [comment]
Renamed the repo for the UI link https://github.com/elastic/enterprise-search-network-drive-connector
