### ISSUE TITLE
Unexpected behaviour of connect_and_get_all_folders method in sync_network_drives.py

### ISSUE THREAD

**Issue by AlanNggg** [elastic/enterprise-search-network-drive-connector#25]
I get this error when network_drive_connector.yml has network_drive.path: "public".

```python
"sync_network_drives.py", line 63, in connect_and_get_all_folders
    path=os.path.join(*self.drive_path.parts[1:]),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: join() missing 1 required positional argument: 'path'
``` 

It seems that network_drive.path must be in form of "public/dummy" etc, and cannot be "public".
Is it an expected behaviour?

**Comment by praveen-elastic** [comment]
Hi, yes, the `drive_path` must be in that form, service-name/folder-path

Here the service-name is the name of the smb share.
You can refer the following line in the documentation. https://github.com/elastic/enterprise-search-network-drive-connector#gather-network-drives-details

Let me know if you need more help :)

**Comment by praveen-elastic** [comment]
I don't have much idea about that, feel free to ask it on Elastic's discuss channel https://discuss.elastic.co/ and any member would help you out.

**Comment by AlanNggg** [comment]
Thank you very much :)
