### ISSUE TITLE
When will this be out of beta and into GA?

### ISSUE THREAD

**Issue by waliur** [elastic/enterprise-search-network-drive-connector#31]
**_⚠️ This connector package is a beta feature. Beta features are subject to change and are not covered by the support SLA of generally available (GA) features. Elastic plans to promote this feature to GA in a future release.
ℹ️ This connector package requires a compatible Elastic subscription level. Refer to the Elastic subscriptions pages for [Elastic Cloud](https://www.elastic.co/subscriptions/cloud) and [self-managed](https://www.elastic.co/subscriptions) deployments._**

We have a need for this in our organisation for millions of documents stored on a shared drive so would like to know current estimates timelines for this.

If timelines are not suitable are there any other commercial and or open source connectors which are compatible which we could look into?

**Comment by danajuratoni** [comment]
@waliur this connector package is not actively developed. Please take a look at our new open-code [Elastic connector](https://www.elastic.co/guide/en/enterprise-search/current/connectors-network-drive.html) that became generally available in [8.10](https://www.elastic.co/guide/en/enterprise-search/current/release-notes-8.10.0.html)!
